#include "codegen.hpp"
#include <cstdint>
#include <iomanip>

namespace miniptx {

// ═══════════════════════════════════════════════════════════════════
//  Helpers
// ═══════════════════════════════════════════════════════════════════

const char* CodeGen::ptxParamType(IRType t) {
    switch (t) {
        case IRType::INT_PTR:
        case IRType::FLOAT_PTR: return ".u64";
        case IRType::FLOAT:     return ".f32";
        default:                return ".s32";
    }
}

std::string CodeGen::ptxParamName(const IRFunction& fn, size_t idx) {
    if (idx < fn.params.size()) {
        std::string name = fn.params[idx].name;
        if (!name.empty() && name[0] == '%') name = name.substr(1);
        return "param_" + name;
    }
    return "param_" + std::to_string(idx);
}

int CodeGen::countInstructions(const std::vector<IRFunction>& fns) const {
    int total = 0;
    for (auto& fn : fns)
        for (auto& b : fn.blocks)
            for (auto& i : b->instructions)
                if (!i.dead) total++;
    return total;
}

// ═══════════════════════════════════════════════════════════════════
//  Debug: .loc directives
// ═══════════════════════════════════════════════════════════════════

void CodeGen::emitLoc(int line, std::ostream& os) {
    if (line > 0 && line != lastLocLine_ && !srcFile_.empty()) {
        os << "    .loc 1 " << line << " 0\n";
        lastLocLine_ = line;
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Top-level
// ═══════════════════════════════════════════════════════════════════

void CodeGen::emitHeader(std::ostream& os) {
    os << "//\n"
       << "// Generated by WarpForge Compiler v0.3\n"
       << "//\n"
       << ".version 7.0\n"
       << ".target sm_80\n"
       << ".address_size 64\n\n";

    // Debug: source file declaration
    if (!srcFile_.empty()) {
        os << ".file 1 \"" << srcFile_ << "\"\n\n";
    }
}

void CodeGen::generate(const std::vector<IRFunction>& fns, std::ostream& os) {
    lastLocLine_ = -1;
    emitHeader(os);
    for (auto& fn : fns) emitFunction(fn, os);
}

// ═══════════════════════════════════════════════════════════════════
//  Function emission
// ═══════════════════════════════════════════════════════════════════

void CodeGen::emitFunction(const IRFunction& fn, std::ostream& os) {
    os << ".visible .entry " << fn.name << "(\n";
    emitParamDecls(fn, os);
    os << ")\n{\n";

    emitRegDecls(os);
    emitParamLoads(fn, os);

    for (auto& b : fn.blocks) {
        if (b->label != "entry") os << b->label << ":\n";

        for (auto& inst : b->instructions) {
            if (inst.dead) continue;
            emitLoc(inst.line, os);
            emitInst(inst, fn, os);
        }
    }

    os << "}\n\n";
}

void CodeGen::emitParamDecls(const IRFunction& fn, std::ostream& os) {
    for (size_t i = 0; i < fn.params.size(); i++) {
        os << "    .param " << ptxParamType(fn.params[i].type) << " "
           << ptxParamName(fn, i);
        if (i + 1 < fn.params.size()) os << ",";
        os << "\n";
    }
}

void CodeGen::emitRegDecls(std::ostream& os) {
    auto decls = ra_.getRegDecls();
    for (auto& d : decls) {
        os << "    .reg " << regClassName(d.rc) << " "
           << regClassPrefix(d.rc) << "<" << d.count << ">;\n";
    }
    os << "\n";
}

void CodeGen::emitParamLoads(const IRFunction& fn, std::ostream& os) {
    for (size_t i = 0; i < fn.params.size(); i++) {
        auto& p = fn.params[i];
        bool isPtr = (p.type == IRType::FLOAT_PTR || p.type == IRType::INT_PTR);
        const char* ldType = isPtr ? ".u64" : (p.type == IRType::FLOAT ? ".f32" : ".s32");
        os << "    ld.param" << ldType << " " << r(p)
           << ", [" << ptxParamName(fn, i) << "];\n";
    }
    os << "\n";
}

// ═══════════════════════════════════════════════════════════════════
//  Instruction selection
// ═══════════════════════════════════════════════════════════════════

void CodeGen::emitInst(const Instruction& inst, const IRFunction& fn,
                       std::ostream& os) {
    (void)fn;
    switch (inst.kind) {

    case InstKind::ASSIGN: {
        const char* mov;
        switch (inst.dst.type) {
            case IRType::FLOAT:     mov = "mov.f32"; break;
            case IRType::INT_PTR:
            case IRType::FLOAT_PTR: mov = "mov.u64"; break;
            case IRType::BOOL:      mov = "mov.pred"; break;
            default:                mov = "mov.s32"; break;
        }
        os << "    " << mov << " " << r(inst.dst) << ", " << r(inst.lhs) << ";\n";
        break;
    }

    case InstKind::BINOP: {
        const char* ptxOp = nullptr;
        if      (inst.op == "add")  ptxOp = "add.s32";
        else if (inst.op == "sub")  ptxOp = "sub.s32";
        else if (inst.op == "mul")  ptxOp = "mul.lo.s32";
        else if (inst.op == "div")  ptxOp = "div.s32";
        else if (inst.op == "fadd") ptxOp = "add.f32";
        else if (inst.op == "fsub") ptxOp = "sub.f32";
        else if (inst.op == "fmul") ptxOp = "mul.f32";
        else if (inst.op == "fdiv") ptxOp = "div.rn.f32";
        else if (inst.op == "and")  ptxOp = "and.pred";
        else if (inst.op == "or")   ptxOp = "or.pred";
        else                        ptxOp = "add.s32";
        os << "    " << ptxOp << " "
           << r(inst.dst) << ", " << r(inst.lhs) << ", " << r(inst.rhs) << ";\n";
        break;
    }

    case InstKind::ICMP: {
        bool isFloat = (inst.lhs.type == IRType::FLOAT);
        const char* suffix = isFloat ? ".f32" : ".s32";
        os << "    setp." << inst.op << suffix << " "
           << r(inst.dst) << ", " << r(inst.lhs) << ", " << r(inst.rhs) << ";\n";
        break;
    }

    case InstKind::LOAD: {
        bool isFloat = (inst.dst.type == IRType::FLOAT);
        const char* ldType = isFloat ? ".f32" : ".s32";
        os << "    cvta.to.global.u64 " << r(inst.ptr) << ", " << r(inst.ptr) << ";\n";
        os << "    ld.global" << ldType << " "
           << r(inst.dst) << ", [" << r(inst.ptr) << "];\n";
        break;
    }

    case InstKind::STORE: {
        bool isFloat = (inst.val.type == IRType::FLOAT);
        const char* stType = isFloat ? ".f32" : ".s32";
        os << "    cvta.to.global.u64 " << r(inst.ptr) << ", " << r(inst.ptr) << ";\n";
        os << "    st.global" << stType << " ["
           << r(inst.ptr) << "], " << r(inst.val) << ";\n";
        break;
    }

    case InstKind::MOV_BUILTIN: {
        std::string sreg;
        if      (inst.builtin.find("threadIdx") != std::string::npos) sreg = "%tid";
        else if (inst.builtin.find("blockIdx")  != std::string::npos) sreg = "%ctaid";
        else if (inst.builtin.find("blockDim")  != std::string::npos) sreg = "%ntid";
        else if (inst.builtin.find("gridDim")   != std::string::npos) sreg = "%nctaid";
        else sreg = "%tid";
        char comp = inst.builtin.back();
        os << "    mov.u32 " << r(inst.dst) << ", "
           << sreg << "." << comp << ";\n";
        break;
    }

    case InstKind::BRANCH:
        os << "    @" << r(inst.cond) << " bra " << inst.true_label << ";\n";
        os << "    bra " << inst.false_label << ";\n";
        break;

    case InstKind::JUMP:
        os << "    bra " << inst.label << ";\n";
        break;

    case InstKind::LABEL:
        break;

    case InstKind::RET:
        os << "    ret;\n";
        break;

    case InstKind::CONST_INT:
        os << "    mov.s32 " << r(inst.dst) << ", " << inst.imm_int << ";\n";
        break;

    case InstKind::CONST_FLOAT: {
        union { float f; uint32_t u; } conv;
        conv.f = inst.imm_float;
        os << "    mov.f32 " << r(inst.dst) << ", 0f"
           << std::hex << std::uppercase << std::setw(8) << std::setfill('0')
           << conv.u << std::dec << ";\n";
        break;
    }

    case InstKind::PHI:
        os << "    // phi " << r(inst.dst);
        for (auto& e : inst.phi_entries)
            os << " [" << r(e.value) << ", " << e.label << "]";
        os << "\n";
        break;
    }
}

} // namespace miniptx
